In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('mimic IV - editada.parquet')
df.head(10)

,inicio_janela,fr,fc,pas,spo,cre,lac,ph,ida,tem_sepse
0,6644643060,22.750000,92.5,88.00,97.00,0.902703,1.7,7.38,52.0,0.0
1,6644646660,20.750000,103.0,90.25,94.25,0.902703,1.7,7.38,52.0,0.0
2,6644650260,20.000000,97.0,95.00,95.00,0.902703,1.7,7.38,52.0,0.0
3,6644653860,21.000000,100.0,86.00,95.00,0.902703,1.7,7.38,52.0,0.0
4,6644657460,16.000000,97.0,93.00,98.00,0.902703,1.7,7.38,52.0,0.0
5,6644661060,19.000000,100.0,90.00,99.00,0.902703,1.7,7.38,52.0,0.0
6,6644664660,21.666667,94.0,84.00,95.00,0.902703,1.7,7.38,52.0,0.0
7,6644668260,20.333333,94.0,84.25,95.00,0.475000,1.7,7.38,52.0,0.0
8,6644700660,20.000000,94.0,85.00,95.00,0.400000,1.7,7.38,52.0,0.0
9,6926374440,23.333333,76.0,153.00,100.00,0.902703,1.7,7.38,73.0,0.0

In [3]:
df = pd.read_parquet('mimic IV.parquet')
df.head(10)

,subject_id,stay_id,janela_index,inicio_janela,charttime_representativo,tem_sepse,fr,fc,pas,spo,cre,lac,ph,ida
0,10000032,39553978,0,2180-07-23 14:11:00,2180-07-23 14:11:00,0.0,22.750000,92.5,88.00,97.00,0.902703,1.7,7.38,52.0
1,10000032,39553978,1,2180-07-23 15:11:00,2180-07-23 16:00:00,0.0,20.750000,103.0,90.25,94.25,0.902703,1.7,7.38,52.0
2,10000032,39553978,2,2180-07-23 16:11:00,2180-07-23 17:00:00,0.0,20.000000,97.0,95.00,95.00,0.902703,1.7,7.38,52.0
3,10000032,39553978,3,2180-07-23 17:11:00,2180-07-23 18:00:00,0.0,21.000000,100.0,86.00,95.00,0.902703,1.7,7.38,52.0
4,10000032,39553978,4,2180-07-23 18:11:00,2180-07-23 19:00:00,0.0,16.000000,97.0,93.00,98.00,0.902703,1.7,7.38,52.0
5,10000032,39553978,5,2180-07-23 19:11:00,2180-07-23 20:00:00,0.0,19.000000,100.0,90.00,99.00,0.902703,1.7,7.38,52.0
6,10000032,39553978,6,2180-07-23 20:11:00,2180-07-23 21:00:00,0.0,21.666667,94.0,84.00,95.00,0.902703,1.7,7.38,52.0
7,10000032,39553978,7,2180-07-23 21:11:00,2180-07-23 21:45:00,0.0,20.333333,94.0,84.25,95.00,0.475000,1.7,7.38,52.0
8,10000032,39553978,16,2180-07-24 06:11:00,2180-07-24 06:35:00,0.0,20.000000,94.0,85.00,95.00,0.400000,1.7,7.38,52.0
9,10000980,39765666,0,2189-06-27 08:54:00,2189-06-27 08:54:00,0.0,23.333333,76.0,153.00,100.00,0.902703,1.7,7.38,73.0